# general configuration

theme = "base16_default"

[editor]
line-number = "relative"
mouse = false
cursorline = true
# cursorcolumn = true
bufferline = "multiple"
auto-save = true
text-width = 80
middle-click-paste = true
auto-completion = true
auto-format = false
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "error"

[editor.statusline]
left = ["file-name", "file-modification-indicator", "spinner", "mode"]
center = ["diagnostics", "workspace-diagnostics"]
right = ["total-line-numbers", "file-line-ending", "position", "position-percentage", "selections", "file-encoding", "version-control"]
mode.normal = ""
mode.insert = "INS"
mode.select = "SEL"

[editor.lsp]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "none"

[editor.whitespace.characters]
space = "-"
tab = "|"
nbsp = "%"

[editor.indent-guides]
render = true
character = "|"

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

# keybinds

## normal mode
[keys.normal]
C-s = ":w"
"ret" = ["open_below", "insert_mode"]
#D = ["select_mode", "goto_line_end", "delete_selection"]
#A-D = ["select_mode", "goto_line_end", "delete_selection_noyank"]
0 = "goto_line_start"
"'" = "keep_primary_selection"
#';' = "command_mode"

## window mode
[keys.normal."C-a"]
'_' = "hsplit"
'h' = "hsplit"
'|' = "vsplit"
'v' = "vsplit"
C-s = "no_op"
C-v = "no_op"

## tabs (submenu in "window mode")
[keys.normal."C-a".w]
c = ":n"
q = ":bc"
o = ":bco"

[keys.normal.g]
t = ":bn"
T = ":bp"
G = "goto_file_end"
j = "goto_file_end"
k = "goto_file_start"

## fun extra keybinds
[keys.normal."+"]
# reload the helix config file
r = ":run-shell-command pkill -USR1 helix"
w = ":toggle soft-wrap.enable"
'+' = ":config-open"
c = ":char"

## mimicking vimrc <leader> binds
[keys.normal.","]
s = ":w"
x = ":wq"
q = ":q!"
',' = "keep_primary_selection"
